### ISSUE TITLE
Issue using git commands from within Gulp

### ISSUE THREAD

**Issue by winzig** [elstudio/actions-js-build#11]
We've been using this build action for a while now to do some Gulp builds, and it's been working great. Recently we modified our Gulp file to use [gulp-git](https://github.com/stevelacy/gulp-git), to help us generate a version number for our package.json, using info from `git describe` and `git rev-parse`. When we try to run this Gulpfile via this action, we get this error:

```
/bin/sh: git: not found
```

We get similar errors even if we explicitly install Git through another (earlier) step in our job, and then use `const exec = require('child_process').exec` to allow us to run git commands directly. 

Both of these work fine locally when we run Gulp. Any ideas for how to work around this issue, or why the Gulpfile cannot access `git` from within an Action?

**Comment by winzig** [comment]
The strange thing is that some `git` commands work, specifically things like `git.commit`. 

But when we use gulp-git's `git.exec` method, that is when we see the "git: not found" errors.

**Comment by elstudio** [comment]
Hi @winzig —

If this is still a problem, mind giving this a try with the new @v4 version of this action? These new versions run directly on the runner, which means git is already installed.

Thanks for using actions-js-build!

**Comment by winzig** [comment]
Hi, given the age of the issue, we had to move on to just handling this manually.
