### ISSUE TITLE
Deploy to GitHub Pages

### ISSUE THREAD

**Issue by alinnert** [elstudio/actions-js-build#2]
I'm trying to use this action to build a static site that then gets published to GitHub Pages. I'm using the variant where the site gets served from the `docs` folder. But for some reason this doesn't work.

By this I mean the changes made by the automated build process get successfully pushed back into the repository. But these changes don't get deployed to gh-pages. On the other hand, the changes I make on and push from my local machine do get deployed.

Do you, by any chance, know why this is happening? Or is there a different approach that is known working?

**Comment by alinnert** [comment]
Wow, I just found the answer to this in this issue: https://github.com/maxheld83/ghpages/issues/1

You can "fix" it by using a manually generated Personal Access Tokens instead of `GITHUB_TOKEN`.

**Comment by elstudio** [comment]
Super!

One other option would be to use an action like https://github.com/peaceiris/actions-gh-pages, which seems to work fine with the built-in `secrets.GITHUB_TOKEN`.
