### ISSUE TITLE
Deploy new files

### ISSUE THREAD

**Issue by terazus** [elstudio/actions-js-build#5]
Hello,
I'm only able to push already existing files back to the branch.
If i create a new file with a script, it's not being correctly added because
```
git diff --quiet 
```
doesn't return anything.
How would you do to also add new files to the commit?

Tx

**Comment by elstudio** [comment]
Thanks for reporting this, @terazus!

I've updated the code to check for new and/or changed files -- so that should fix your issue. 

Please confirm, and re-open this if need be.

-e

**Comment by terazus** [comment]
cool tx, will try it out today !
